

GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json  

{
    "email": "test@test.com",
    "password": "test"
}

###

POST http://localhost:3000/api/auth/signin
Content-Type: application/json  

{
    "email": "test@test.com",
    "password": "test"
}